# Generated by Django 2.0.5 on 2018-05-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_model', models.CharField(max_length=3000)),
                ('model_parameters', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('train_size', models.IntegerField()),
                ('test_size', models.IntegerField()),
                ('model_measures', models.CharField(max_length=300)),
                ('model_scores', models.CharField(max_length=300)),
                ('model_name', models.CharField(max_length=300)),
            ],
        ),
    ]
