# Generated by Django 2.0.5 on 2018-05-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainedmodels',
            old_name='picked_model',
            new_name='pickled_model',
        ),
    ]
